[phases.setup]
nixPkgs = ['nodejs', 'php82', 'php82Packages.composer']

[phases.install]
cmds = ['composer install --no-dev --optimize-autoloader', 'npm ci']

[phases.build]
cmds = ['npm run build']

[start]
cmd = 'touch /app/database/database.sqlite && php artisan migrate --force && php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=$PORT --no-reload'
